[WIP] Allow water evaporation
OPM/opm-material pull request #429
Opened 2020-09-23 07:29 UTC by goncalvesmachadoc

2021-09-28 10:25 UTC, goncalvesmachadoc commented
Hi @totto82 , could you review this code?

2021-09-28 11:10 UTC, totto82 requested changes
Thanks for the contribution. These changes looks good itself but needs to be merged together with changes in opm-common (https://github.com/OPM/opm-common/pull/1956) and opm-models/opm-simulators (no PR yet) since this changes the number of template parameters in the BlackoilFluidState.

2021-09-28 11:10 UTC, totto82 commented on opm/material/fluidstates/BlackOilFluidState.hpp
>            unsigned numStoragePhases = FluidSystem::numPhases>
Suggestion: Rename to enableSaltPrecipitation?

2021-09-29 09:33 UTC, totto82 commented
jenkins build this please

2021-11-29 15:41 UTC, goncalvesmachadoc commented
Updated the template parameters in https://github.com/OPM/opm-models/pull/678 and https://github.com/OPM/opm-simulators/pull/3715

2021-11-30 11:26 UTC, totto82 commented
Thanks for the update. The code change look ok from my perspective. Since these PRs cross repository, some more Jenkins testing will be needed. I will start the process. I assume there will be more PRs in opm-models and opm-simulators that implement the actual model so lets get these "Preparation" PRs merged!

2021-11-30 11:26 UTC, totto82 commented
jenkins build this please

2021-11-30 11:44 UTC, totto82 commented
jenkins build this opm-common=1956 opm-models=678 opm-simulators=3715 please

2021-12-09 14:37 UTC, merged